# Generated by Django

from django.db import migrations
from django.contrib.auth.models import Group, User

GROUPS = ['Administrator', 'Veterinarian', 'Assistant', 'Receptionist', 'Accountant']

USERS = [
    (
        'su_smith', 'John', 'Smith', 'dr.smith@vetclinic.com', 'password123', True, ['Administrator']
    ),
    (
        'dr_jones', 'Emily', 'Jones', 'dr.jones@vetclinic.com', 'password123', False, ['Veterinarian']
    ),
    (
        'as_davis', 'Mark', 'Davis', 'm.davis@vetclinic.com', 'password123', False, ['Assistants']
    ),
    (
        'rec_brown', 'Sarah', 'Brown', 's.browm@vetclinic.com', 'password123', False, ['Receptionist']
    ),
    (
        'acc_white', 'Michael', 'White', 'm.white', 'password123', False, ['Accountant']
    ),
]

def forwards_func(apps, schema_editor):
    for group_name in GROUPS:
        Group.objects.get_or_create(name=group_name)

    for username, first_name, last_name, email, password, is_superuser, user_groups in USERS:
        if User.objects.filter(username=username).exists():
            continue

        if is_superuser:
            user = User.objects.create_superuser(
                username=username,
                email=email,
                password=password,
                first_name=first_name,
                last_name=last_name
            )
        else:
            user = User.objects.create_user(
                username=username,
                email=email,
                password=password,
                first_name=first_name,
                last_name=last_name,
                is_staff=True
            )

        for group_name in user_groups:
            group = Group.objects.get(name=group_name)
            user.groups.add(group)

def reverse_func(apps, schema_editor):
    for username, _, _, _, _, _, _ in USERS:
        User.objects.filter(username=username).delete()

    for group_name in GROUPS:
        Group.objects.filter(name=group_name).delete()


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]